### ISSUE TITLE
I have a few questions 

### ISSUE THREAD

**Issue by coffeebond** [micans/sylamer#1]
Hi,

I have a few questions about sylamer and hope you can help clarify.

1) for the `-m` option, if I use 4, does it mean the correction is 4th order Markov model, i.e. using frequencies of 4mers and 5mers to calculate expected frequencies of 6mer? 

2) For a specific kmer (word) you use the expected number of counts (based on the Markov model) in the population to replace the actual count of that kmer in the population for the hypergeometric test, but you also multiply it by a factor u_r/u_e, where u_r is the number of observed counts in the population and u_e is the number of expected counts in the population. Does that mean you return this (expected counts) to the actual counts in the population? So this expected counts was not used at all? 

3) In sylamer, you use kmer (word) counts in the leading bin for the statistical test. I assume you pool all sequences in the bin together to calculate the expected frequency of each kmer, right? Have you compared it to using the number of sequences containing the kmer for the test? In this case, each drawing would be a sequence (from a gene, one entry in the fasta file) and the number of black balls would be the number of sequences that contain at least one such kmer. I think this is what was used in Farh et.al, 2005, although they didn't use a hypergeometric test. 

Thank you!

**Comment by micans** [comment]
Hello,

1. I made the choice in the past, perhaps unfortunately, to make -m refer to the longer word. So -m 4 uses frequencies of 3mers and 4mers to calculate expected frequencies of k-mers (-k argument, default value 6).  (In the source code this is evident at https://github.com/micans/sylamer/blob/aa75c3584797c0c15f860addb645f7bc1dd7627d/src/sylamer.c#L1566).

2. This multiplication is a moderation factor so that at the very end of the list of sequences the moderated expected frequencies are identical again to the observed frequencies - otherwise the strongest effect would often be observed at/near the end of the list (the computed probabilities keep ballooning as the entire list often has biases, nearly always gc/at). This moderation factor causes the hypergeometric test to revert to 'probability of taking all black balls when I take all balls from the vase', symmetrically to the test 'probability of taking zero black balls when I take no balls at all from the vase' at the very start of the list. This was proposed by Cei Abreu-Goodger; I believe it followed the approach taken in another publication.

3. [edited] Yes that is right, the background is total sequence length in the bin. We did compare it to using the number of sequences. Sylamer provides the option `-threshold <num>  (count sequences where per-sequence occurrences >= <num>)` for this. This is long ago now but in nearly all scenarios the sequence-length background worked much better. I do not remember a scenario where `-threshold` worked even a little bit better. The option to test this mode is there if you wish to.

**Comment by coffeebond** [comment]
Hi,

Thank you. This is very helpful. 

About the second point, how do you decide when to switch back to the observed counts from the expected counts? Is there a criterion?

**Comment by micans** [comment]
Hello,

this is entirely achieved by the moderation factor itself, there is no switching. The factor works such that in the end it cancels out the difference entirely, before that it has a moderating effect. Its moderating effect changes along the list of genes. EDIT: the factor is not constant, it depends on the k-mer and the gene list prefix being considered.

**Comment by coffeebond** [comment]
Oh, do you mean that u_e is actually a constant, i.e. not changing in different leading edge of the bins? So you calculate u_e using the entire sequences. I misunderstood it originally and thought it was changing based on the bins.

**Comment by coffeebond** [comment]
Sorry, one more question. Do you ever see a scenario where modulated kmer count in the population (expected kmer count in the population * u_r/u_e) becomes larger than the kmer count in the sample for certain leading bins? If so, how do you deal with that?

**Comment by micans** [comment]
I've dug in the source a bit. This is with a slight caveat as it has been more than ten years, the code is quite abstracted and has a lot of branches for more experimental things we looked at. The expected count in leading window y is computed as
```
                            elocal_y * bg_count_y
 expected_count_y =             ------------
                                  eglobal_y

```
This can be viewed as the locally (under Markov model) expected count (`elocal_y`) moderated by the actual global count of the k-mer (`bg_count_y`)  relative to the expected global count of the k-mer (`eglobal_y`). In the last window, `elocal_y` and `eglobal_y` cancel and the expected count then is thus equal to the global (actual) count.

**Comment by micans** [comment]
> Sorry, one more question. Do you ever see a scenario where modulated kmer count in the population (expected kmer count in the population * u_r/u_e) becomes larger than the kmer count in the sample for certain leading bins? If so, how do you deal with that?

There is a check in the code
```
if (bg_count_yy < window_count_y) {     /* bg_count_yy reflects expected counts if Markov model is used */
  bg_count_yy = window_count_y;
  deus_ex_machina++;                         /* this is tracked and reported */
}
```

**Comment by coffeebond** [comment]
Thank you. These all make sense now.
